extends:
   [
      'stylelint-config-standard-scss',
      'stylelint-config-standard',
      'stylelint-config-prettier',
      'stylelint-prettier/recommended',
   ]
rules:
   color-hex-length: long,
   selector-class-pattern: false,
   rule-empty-line-before: false
