extends:
   [
      'stylelint-config-standard-scss',
      'stylelint-config-standard',
      'stylelint-config-prettier',
      'stylelint-prettier/recommended',
   ]
rules:
   {
      'font-family-no-missing-generic-family-keyword': null,
      'declaration-block-no-redundant-longhand-properties': null,
      'selector-class-pattern':
         [
            '^([a-z][a-z0-9]*)([_-]*[a-z0-9]+)*$',
            { 'message': 'Expected custom property name to be kebab-case' },
         ],
   }
