extends:
   [
      'stylelint-config-standard-scss',
      'stylelint-config-standard',
      'stylelint-config-prettier',
      'stylelint-prettier/recommended',
   ]
rules:
   color-hex-length: long
